import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F8FAFC",
    },
    headerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 20,
    },
    mainTittle: {
        fontSize: 28,
        fontWeight: "800",
        color: "#0F172A",
    },
    actionButton: {
        padding: 8,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        shadowColor: "#94A3B8",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: "#F1F5F9",
    },
    disabledButton: {
        opacity: 0.4,
    },
    contentArea: {
        flex: 1,
        paddingHorizontal: 16,
        paddingBottom: 120, // leave room for bottom tabs
    },
    imageBoxContainer: {
        flex: 1,
        width: "100%",
        backgroundColor: "#FFFFFF",
        borderRadius: 24,
        shadowColor: "#94A3B8",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 15,
        elevation: 4,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        overflow: "hidden", // Keeps image inside radius
        position: "relative",
    },
    imageContent: {
        width: "100%",
        height: "100%",
    },
    editFloatingButton: {
        position: "absolute",
        bottom: 20,
        right: 20,
        backgroundColor: "#4F46E5",
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 999,
        gap: 8,
        shadowColor: "#4F46E5",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    editFloatingText: {
        color: "#FFFFFF",
        fontWeight: "700",
        fontSize: 14,
    },
    uploadBox: {
        flex: 1,
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 24,
        backgroundColor: "#F1F5F9",
        borderWidth: 2,
        borderColor: "#CBD5E1",
        borderStyle: "dashed",
    },
    uploadIconWrapper: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: "#EEF2FF",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    uploadTitle: {
        fontSize: 20,
        color: "#1E293B",
        fontWeight: "700",
        marginBottom: 8,
    },
    uploadSubtitle: {
        fontSize: 14,
        color: "#64748B",
        fontWeight: "500",
    },

    /* Tabular UI Styles */
    tableContainer: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        borderRadius: 24,
        shadowColor: "#94A3B8",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 15,
        elevation: 4,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        overflow: "hidden",
    },
    tableHeaderRow: {
        flexDirection: "row",
        backgroundColor: "#F8FAFC",
        borderBottomWidth: 1,
        borderBottomColor: "#E2E8F0",
        paddingVertical: 14,
        paddingHorizontal: 16,
    },
    tableHeaderCell: {
        fontSize: 12,
        fontWeight: "700",
        color: "#64748B",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    timeCol: { flex: 0.35 },
    detailsCol: { flex: 0.65 },
    tableRow: {
        flexDirection: "row",
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#F1F5F9",
        alignItems: "center",
    },
    tableCellTextPrimary: {
        fontSize: 15,
        fontWeight: "700",
        color: "#0F172A",
        marginBottom: 2,
    },
    tableCellTextSecondary: {
        fontSize: 13,
        fontWeight: "500",
        color: "#64748B",
    },
    tableCellTime: {
        fontSize: 14,
        fontWeight: "700",
        color: "#4F46E5",
    },
    typePill: {
        alignSelf: "flex-start",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: "#EEF2FF",
        borderWidth: 1,
        borderColor: "#C7D2FE",
        marginTop: 6,
    },
    typePillText: {
        fontSize: 11,
        fontWeight: "700",
        color: "#4F46E5",
        textTransform: "uppercase",
    },

    /* Loading Overlay */
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(255,255,255,0.85)",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 20,
        borderRadius: 24,
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        fontWeight: "700",
        color: "#4F46E5",
    },

    /* Day Selection Chips */
    daySelectorScroller: {
        maxHeight: 60,
    },
    daySelectorRow: {
        flexDirection: "row",
        paddingVertical: 8,
        paddingHorizontal: 2,
        marginBottom: 8,
    },
    dayChip: {
        height: 38,
        paddingHorizontal: 20,
        borderRadius: 20,
        backgroundColor: "#FFFFFF",
        marginRight: 10,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        alignItems: "center",
        justifyContent: "center",
    },
    dayChipActive: {
        backgroundColor: "#4F46E5",
        borderColor: "#4F46E5",
        shadowColor: "#4F46E5",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    dayText: {
        fontSize: 14,
        fontWeight: "700",
        color: "#64748B",
    },
    dayTextActive: {
        color: "#FFFFFF",
    },
    /* Spreadsheet Grid Styles */
    gridWrapper: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        overflow: "hidden",
        marginBottom: 16,
    },
    gridRow: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderBottomColor: "#E2E8F0",
    },
    gridHeaderCell: {
        borderRightWidth: 1,
        borderRightColor: "#E2E8F0",
        padding: 8,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#F8FAFC",
    },
    gridDayCell: {
        width: 70, // Matches CELL_DAY
        borderRightWidth: 1,
        borderRightColor: "#E2E8F0",
        padding: 8,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#F8FAFC",
    },
    gridDayText: {
        fontWeight: "800",
        color: "#0F172A",
    },
    gridDataCell: {
        borderRightWidth: 1,
        borderRightColor: "#E2E8F0",
        padding: 8,
        justifyContent: "center",
    },
    gridCellTextPrimary: {
        fontSize: 12,
        fontWeight: "700",
        color: "#0F172A",
        textAlign: "center",
        marginBottom: 4,
    },
    gridCellTextSecondary: {
        fontSize: 10,
        fontWeight: "600",
        color: "#64748B",
        textAlign: "center",
    },
    // Cell Background States
    bgLecture: { backgroundColor: "#FFFFFF" },
    bgLab: { backgroundColor: "#F0FDF4" },
    bgLunch: { backgroundColor: "#FFF7ED", alignItems: "center" },
    bgTutorial: { backgroundColor: "#EEF2FF" },
    bgEmpty: { backgroundColor: "#F8FAFC" },
    textLecture: { color: "#0F172A" },
    textLab: { color: "#16A34A" },
    textLunch: { color: "#EA580C" },
    textTutorial: { color: "#4F46E5" }
});